void enable_debug();
void delayMs(int milliseconds);
void inititalize_display();
void print_debug(int page, char* string);
void print_int(int value);
void clearScreen();
void paintOnePixel(int x, int y);
void paintPic(int x, int y, const char* pic);
void printText(int x, int y, char* str);
void updateScreen();
